from PySide6 import QtCore, QtGui, QtWidgets

class CsvSelect(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 200)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_csv_button = QtWidgets.QPushButton(self.central_widget)
        self.select_csv_button.setMinimumSize(QtCore.QSize(0, 41))
        self.select_csv_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.select_csv_button.setObjectName("select_csv_button")
        self.verticalLayout.addWidget(self.select_csv_button)
        self.csv_path_label = QtWidgets.QLabel(self.central_widget)
        self.csv_path_label.setMinimumSize(QtCore.QSize(0, 31))
        self.csv_path_label.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.csv_path_label.setWordWrap(True)
        self.csv_path_label.setObjectName("csv_path_label")
        self.verticalLayout.addWidget(self.csv_path_label)
        self.run_type_horiz = QtWidgets.QHBoxLayout()
        self.run_type_horiz.setObjectName("run_type_horiz")
        self.run_type_combo = QtWidgets.QComboBox(self.central_widget)
        self.run_type_combo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.run_type_combo.setObjectName("run_type_combo")
        self.run_type_horiz.addWidget(self.run_type_combo)
        self.iterations_spin = QtWidgets.QSpinBox(self.central_widget)
        self.iterations_spin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.iterations_spin.setStyleSheet("")
        self.iterations_spin.setMinimum(1)
        self.iterations_spin.setMaximum(999)
        self.iterations_spin.setObjectName("iterations_spin")
        self.run_type_horiz.addWidget(self.iterations_spin)
        self.verticalLayout.addLayout(self.run_type_horiz)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.okay_button = QtWidgets.QPushButton(self.central_widget)
        self.okay_button.setMinimumSize(QtCore.QSize(0, 41))
        self.okay_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.okay_button.setObjectName("okay_button")
        self.verticalLayout.addWidget(self.okay_button)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Olfactory Controller"))
        self.select_csv_button.setText(_translate("MainWindow", "Select CSV File"))
        self.csv_path_label.setText(_translate("MainWindow", "No File Selected"))
        self.okay_button.setText(_translate("MainWindow", "Okay"))